import Head from 'next/head'
import Image from 'next/image'
import { checkout } from '../checkout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stripe App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Shop World</a>
        </h1>

        <div className={styles.grid}>

          <div className={styles.card}>
            <img src='assests/nikeshoes.jpeg' width={200} height={300} />
            <h2>Nike Shoes</h2>
            <p>Best Nike shoes.</p>
            <button onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1LzvoiSDmyMtTThlof4pVwil", // price API id
                    quantity: 1
                  }
                ]
              })
            }}>Buy</button>
          </div>

          <div className={styles.card}>
            <img src='assests/niketshirt.jpeg' width={200} height={300} />
            <h2>Nike T-shirt</h2>
            <p>Best Nike t-shirt.</p>
            <button onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1LzvpqSDmyMtTThlMVz4MuvQ", // price API id
                    quantity: 1
                  }
                ]
              })
            }}>Buy</button>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <div>
          Powered by
          <strong> Abhishek </strong>
        </div>
      </footer>
    </div>
  )
}
